let sync_dispatch         = "__ES__wrapper__syncDispatch"
let sync_dispatch_native  = "__ES__wrapper__sDispatch"
let async_dispatch        = "__ES__wrapper__asyncDispatch"
let async_dispatch_native = "__ES__wrapper__aDispatch"
let add_handler           = "__ES__wrapper__addHandler"
let remove_handler        = "__ES__wrapper__removeHandler"
let await                 = "__ES__wrapper__js_await"
let schedule              = "__ES__wrapper__schedule"
let schedule_with_time    = "__ES__wrapper__schedule_with_time"

let message_event         = "message"
let timing_event          = "time"
let schedule_event        = "schedule"