/*
* @id initUIEventsFiles
*/
var initUIEventsFiles = function(){

    var files = {} 
   
   
    files["AddEventListenerOptionsOnce.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"AddEventListenerOptions.once"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["AddEventListenerOptionsPassive.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"EventListenerOptions.passive"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["CustomEvent.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"CustomEvent"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventCancelBubble.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"Event.cancelBubble"}]},{"type":"element","name":"meta","attributes":[{"name":"content","value":"dom","elements":[]},{"name":"name","value":"flags","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"outer","elements":[]}],"elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"middle","elements":[]}],"elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"inner","elements":[]}]}]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventConstants.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Event constants"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"../constants.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventConstructors.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Event constructors"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDefaultPreventedAfterDispatch.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"Event.defaultPrevented is not reset after dispatchEvent()"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"input","attributes":[{"name":"id","value":"target","elements":[]},{"name":"type","value":"hidden","elements":[]},{"name":"value","value":"","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDefaultPrevented.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Event.defaultPrevented"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchBubbleCanceled.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Setting cancelBubble=true prior to dispatchEvent()"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"table","attributes":[{"name":"border","value":"1","elements":[]},{"name":"id","value":"table","elements":[]},{"name":"style","value":"display: none","elements":[]}],"elements":[{"type":"element","name":"tbody","attributes":[{"name":"id","value":"table-body","elements":[]}],"elements":[{"type":"element","name":"tr","attributes":[{"name":"id","value":"table-row","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"table-cell","elements":[]}],"elements":[{"type":"text","text":"Shady Grove"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Aeolian"}]}]},{"type":"element","name":"tr","attributes":[{"name":"id","value":"parent","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"target","elements":[]}],"elements":[{"type":"text","text":"Over the river, Charlie"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Dorian"}]}]}]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchBubblesFalse.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":" Event.bubbles attribute is set to false "}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"table","attributes":[{"name":"border","value":"1","elements":[]},{"name":"id","value":"table","elements":[]},{"name":"style","value":"display: none","elements":[]}],"elements":[{"type":"element","name":"tbody","attributes":[{"name":"id","value":"table-body","elements":[]}],"elements":[{"type":"element","name":"tr","attributes":[{"name":"id","value":"table-row","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"table-cell","elements":[]}],"elements":[{"type":"text","text":"Shady Grove"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Aeolian"}]}]},{"type":"element","name":"tr","attributes":[{"name":"id","value":"parent","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"target","elements":[]}],"elements":[{"type":"text","text":"Over the river, Charlie"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Dorian"}]}]}]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchBubblesTrue.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":" Event.bubbles attribute is set to false "}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"table","attributes":[{"name":"border","value":"1","elements":[]},{"name":"id","value":"table","elements":[]},{"name":"style","value":"display: none","elements":[]}],"elements":[{"type":"element","name":"tbody","attributes":[{"name":"id","value":"table-body","elements":[]}],"elements":[{"type":"element","name":"tr","attributes":[{"name":"id","value":"table-row","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"table-cell","elements":[]}],"elements":[{"type":"text","text":"Shady Grove"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Aeolian"}]}]},{"type":"element","name":"tr","attributes":[{"name":"id","value":"parent","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"target","elements":[]}],"elements":[{"type":"text","text":"Over the river, Charlie"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Dorian"}]}]}]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchClick.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Synthetic click event \"magic\""}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"div","attributes":[{"name":"id","value":"dump","elements":[]},{"name":"style","value":"display:none","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchDetachedClick.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Click event on an element not in the document"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchHandlersChanged.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":" Dispatch additional events inside an event listener "}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"table","attributes":[{"name":"border","value":"1","elements":[]},{"name":"id","value":"table","elements":[]},{"name":"style","value":"display: none","elements":[]}],"elements":[{"type":"element","name":"tbody","attributes":[{"name":"id","value":"table-body","elements":[]}],"elements":[{"type":"element","name":"tr","attributes":[{"name":"id","value":"table-row","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"table-cell","elements":[]}],"elements":[{"type":"text","text":"Shady Grove"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Aeolian"}]}]},{"type":"element","name":"tr","attributes":[{"name":"id","value":"parent","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"target","elements":[]}],"elements":[{"type":"text","text":"Over the river, Charlie"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Dorian"}]}]}]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchMultipleCancelBubble.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Multiple dispatchEvent() and cancelBubble"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"div","attributes":[{"name":"id","value":"parent","elements":[]},{"name":"style","value":"display: none","elements":[]}],"elements":[{"type":"element","name":"input","attributes":[{"name":"id","value":"target","elements":[]},{"name":"type","value":"hidden","elements":[]},{"name":"value","value":"","elements":[]}]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchMultipleStopPropagation.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":" Multiple dispatchEvent() and stopPropagation() "}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"div","attributes":[{"name":"id","value":"parent","elements":[]},{"name":"style","value":"display: none","elements":[]}],"elements":[{"type":"element","name":"input","attributes":[{"name":"id","value":"target","elements":[]},{"name":"type","value":"hidden","elements":[]},{"name":"value","value":"","elements":[]}]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchOmittedCapture.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"EventTarget.addEventListener: capture argument omitted"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"table","attributes":[{"name":"border","value":"1","elements":[]},{"name":"id","value":"table","elements":[]},{"name":"style","value":"display: none","elements":[]}],"elements":[{"type":"element","name":"tbody","attributes":[{"name":"id","value":"table-body","elements":[]}],"elements":[{"type":"element","name":"tr","attributes":[{"name":"id","value":"table-row","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"table-cell","elements":[]}],"elements":[{"type":"text","text":"Shady Grove"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Aeolian"}]}]},{"type":"element","name":"tr","attributes":[{"name":"id","value":"parent","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"target","elements":[]}],"elements":[{"type":"text","text":"Over the river, Charlie"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Dorian"}]}]}]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchOnDisabledElements.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"meta","attributes":[{"name":"content","value":"long","elements":[]},{"name":"name","value":"timeout","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"Events must dispatch on disabled elements"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testdriver.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testdriver-vendor.js","elements":[]}]},{"type":"element","name":"style","elements":[{"type":"text","text":"\n  @keyframes fade {\n    0% {\n      opacity: 1;\n    }\n    100% {\n      opacity: 0;\n    }\n  }\n"}]}]},{"type":"element","name":"body"}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchOrder.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Event phases order"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"div","attributes":[{"name":"id","value":"parent","elements":[]}],"elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"child","elements":[]}]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchOtherDocument.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Custom event on an element in another document"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchPropagationStopped.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":" Calling stopPropagation() prior to dispatchEvent() "}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"table","attributes":[{"name":"border","value":"1","elements":[]},{"name":"id","value":"table","elements":[]},{"name":"style","value":"display: none","elements":[]}],"elements":[{"type":"element","name":"tbody","attributes":[{"name":"id","value":"table-body","elements":[]}],"elements":[{"type":"element","name":"tr","attributes":[{"name":"id","value":"table-row","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"table-cell","elements":[]}],"elements":[{"type":"text","text":"Shady Grove"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Aeolian"}]}]},{"type":"element","name":"tr","attributes":[{"name":"id","value":"parent","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"target","elements":[]}],"elements":[{"type":"text","text":"Over the river, Charlie"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Dorian"}]}]}]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchRedispatch.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"EventTarget#dispatchEvent(): redispatching a native event"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchReenter.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":" Dispatch additional events inside an event listener "}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"table","attributes":[{"name":"border","value":"1","elements":[]},{"name":"id","value":"table","elements":[]},{"name":"style","value":"display: none","elements":[]}],"elements":[{"type":"element","name":"tbody","attributes":[{"name":"id","value":"table-body","elements":[]}],"elements":[{"type":"element","name":"tr","attributes":[{"name":"id","value":"table-row","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"table-cell","elements":[]}],"elements":[{"type":"text","text":"Shady Grove"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Aeolian"}]}]},{"type":"element","name":"tr","attributes":[{"name":"id","value":"parent","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"target","elements":[]}],"elements":[{"type":"text","text":"Over the river, Charlie"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Dorian"}]}]}]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchTargetMoved.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":" Determined event propagation path - target moved "}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"table","attributes":[{"name":"border","value":"1","elements":[]},{"name":"id","value":"table","elements":[]},{"name":"style","value":"display: none","elements":[]}],"elements":[{"type":"element","name":"tbody","attributes":[{"name":"id","value":"table-body","elements":[]}],"elements":[{"type":"element","name":"tr","attributes":[{"name":"id","value":"table-row","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"table-cell","elements":[]}],"elements":[{"type":"text","text":"Shady Grove"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Aeolian"}]}]},{"type":"element","name":"tr","attributes":[{"name":"id","value":"parent","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"target","elements":[]}],"elements":[{"type":"text","text":"Over the river, Charlie"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Dorian"}]}]}]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchTargetRemoved.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"Determined event propagation path - target removed"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"table","attributes":[{"name":"border","value":"1","elements":[]},{"name":"id","value":"table","elements":[]},{"name":"style","value":"display: none","elements":[]}],"elements":[{"type":"element","name":"tbody","attributes":[{"name":"id","value":"table-body","elements":[]}],"elements":[{"type":"element","name":"tr","attributes":[{"name":"id","value":"table-row","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"table-cell","elements":[]}],"elements":[{"type":"text","text":"Shady Grove"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Aeolian"}]}]},{"type":"element","name":"tr","attributes":[{"name":"id","value":"parent","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"target","elements":[]}],"elements":[{"type":"text","text":"Over the river, Charlie"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Dorian"}]}]}]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchThrowing.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"Throwing in event listeners"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventInitWhileDispatching.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"Re-initializing events while dispatching them"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventInitEvent.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Event.initEvent"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventPropagation.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Event propagation tests"}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventReturnValue.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"Event.returnValue"}]},{"type":"element","name":"meta","attributes":[{"name":"content","value":"dom","elements":[]},{"name":"name","value":"flags","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventSubclassesConstructors.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"Event constructors"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventTimestampHighResolution.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body"}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventTimestampSafeResolution.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body"}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventTypeEmpty.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Event.type set to the empty string"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventType.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Event.type"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventListenerHandleEvent.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"EventListener::handleEvent()"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventListenerIncumbentGlobal1.sub.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title"},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"iframe","attributes":[{"name":"src","value":"{{location[scheme]}}://{{domains[www1]}}:{{ports[http][0]}}{{location[path]}}/../EventListener-incumbent-global-subframe-1.sub.html","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventListenerIncumbentGlobal2.sub.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title"},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"iframe","attributes":[{"name":"src","value":"{{location[scheme]}}://{{domains[www1]}}:{{ports[http][0]}}{{location[path]}}/../EventListener-incumbent-global-subframe-2.sub.html","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventListenerIncumbentGlobalSubframe1.sub.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head"},{"type":"element","name":"body","elements":[{"type":"element","name":"iframe","attributes":[{"name":"src","value":"{{location[scheme]}}://{{domains[www2]}}:{{ports[http][0]}}{{location[path]}}/../EventListener-incumbent-global-subsubframe.sub.html","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventListenerIncumbentGlobalSubframe2.sub.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head"},{"type":"element","name":"body","elements":[{"type":"element","name":"iframe","attributes":[{"name":"src","value":"{{location[scheme]}}://{{domains[www2]}}:{{ports[http][0]}}{{location[path]}}/../EventListener-incumbent-global-subsubframe.sub.html","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventListenerIncumbentGlobalSubsubframe.sub.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head"},{"type":"element","name":"body"}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventListenerInvokeLegacy.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"Invoke legacy event listener"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]},{"type":"element","name":"style","elements":[{"type":"text","text":"\n  @keyframes test {\n    0% { color: red; }\n    100% { color: green; }\n  }\n"}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventListenerOptionsCapture.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"EventListenerOptions.capture"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventTargetAddEventListener.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"EventTarget.addEventListener"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventTargetDispatchEventReturnValue.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"EventTarget.dispatchEvent: return value"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]},{"type":"element","name":"table","attributes":[{"name":"border","value":"1","elements":[]},{"name":"id","value":"table","elements":[]},{"name":"style","value":"display: none","elements":[]}],"elements":[{"type":"element","name":"tbody","attributes":[{"name":"id","value":"table-body","elements":[]}],"elements":[{"type":"element","name":"tr","attributes":[{"name":"id","value":"table-row","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"table-cell","elements":[]}],"elements":[{"type":"text","text":"Shady Grove"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Aeolian"}]}]},{"type":"element","name":"tr","attributes":[{"name":"id","value":"parent","elements":[]}],"elements":[{"type":"element","name":"td","attributes":[{"name":"id","value":"target","elements":[]}],"elements":[{"type":"text","text":"Over the river, Charlie"}]},{"type":"element","name":"td","elements":[{"type":"text","text":"Dorian"}]}]}]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventTargetDispatchEvent.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"EventTarget.dispatchEvent"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/dom/nodes/Document-createEvent.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventTargetRemoveEventListener.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"EventTarget.removeEventListener"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["DocumentLevelTouchmoveEventListenerPassiveByDefault.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Default passive document level touchmove event listener test"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testdriver.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testdriver-actions.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testdriver-vendor.js","elements":[]}]}]},{"type":"element","name":"body","attributes":[{"name":"onload","value":"runTest()","elements":[]}],"elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"touchDiv","elements":[]}]},{"type":"element","name":"style","elements":[{"type":"text","text":"\n#touchDiv {\n  width: 100px;\n  height: 100px;\n}\n"}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["DocumentLevelWheelEventListenerPassiveByDefaultManual.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Default passive document level wheel event listener manual test"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","attributes":[{"name":"onload","value":"runTest()","elements":[]}],"elements":[{"type":"element","name":"div","elements":[{"type":"text","text":"This is a manual test since there is no way to synthesize wheel events.\nScroll by wheel in the middle of the page to run the test."}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDisabledDynamic.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":[{"name":"charset","value":"utf-8","elements":[]}]},{"type":"element","name":"title","elements":[{"type":"text","text":"Test that disabled is honored immediately in presence of dynamic changes"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"input","attributes":[{"name":"disabled","value":"","elements":[]},{"name":"type","value":"button","elements":[]},{"name":"value","value":"Click","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventGlobal.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"window.event tests"}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"log","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["ShadowRelatedTarget.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharness.js","elements":[]}]},{"type":"element","name":"script","attributes":[{"name":"src","value":"/resources/testharnessreport.js","elements":[]}]},{"type":"comment","comment":"\n  This test is adopted from Olli Pettay's test case at\n  http://mozilla.pettay.fi/shadow_focus.html\n"}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"host","elements":[]}]},{"type":"element","name":"input","attributes":[{"name":"id","value":"lightInput","elements":[]}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchOrderAtTarget.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"title","elements":[{"type":"text","text":"Listeners are invoked in correct order (AT_TARGET phase)"}]},{"type":"element","name":"script","attributes":{"src":"/resources/testharness.js"}},{"type":"element","name":"script","attributes":{"src":"/resources/testharnessreport.js"}}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":{"id":"log"}}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventDispatchDetachedInputAndChange.html"] = 
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":{"charset":"utf-8"}},{"type":"element","name":"title","elements":[{"type":"text","text":"input and change events for detached checkbox and radio elements"}]},{"type":"element","name":"script","attributes":{"src":"/resources/testharness.js"}},{"type":"element","name":"script","attributes":{"src":"/resources/testharnessreport.js"}}]},{"type":"element","name":"body"}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventStopImmediatePropagation.html"] =
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":{"charset":"utf-8"}},{"type":"element","name":"title","elements":[{"type":"text","text":"Event's stopImmediatePropagation"}]},{"type":"element","name":"script","attributes":{"src":"/resources/testharness.js"}},{"type":"element","name":"script","attributes":{"src":"/resources/testharnessreport.js"}}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":[{"name":"id","value":"target"}]}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventTargetAddRemoveListener.html"] =
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":{"charset":"utf-8"}},{"type":"element","name":"title","elements":[{"type":"text","text":"EventTarget's addEventListener + removeEventListener"}]},{"type":"element","name":"script","attributes":{"src":"/resources/testharness.js"}},{"type":"element","name":"script","attributes":{"src":"/resources/testharnessreport.js"}}]},{"type":"element","name":"body","elements":[{"type":"element","name":"div","attributes":{"id":"log"}}]}]}],"declaration": {"type": "DOCTYPE"}}
    files["EventTargetThisOfListener.html"] =
        {"elements":[{"type":"doctype","doctype":"html"},{"type":"element","name":"html","elements":[{"type":"element","name":"head","elements":[{"type":"element","name":"meta","attributes":{"charset":"utf-8"}},{"type":"element","name":"title","elements":[{"type":"text","text":"EventTarget listeners this value"}]},{"type":"element","name":"script","attributes":{"src":"/resources/testharness.js"}},{"type":"element","name":"script","attributes":{"src":"/resources/testharnessreport.js"}}]},{"type":"element","name":"body"}]}],"declaration": {"type": "DOCTYPE"}}
    

    /*
    * @id getUIEventsJSON
    */
    function getUIEventsJSON(filename){
        return files[filename];
    }

    return {'getJSON': getUIEventsJSON, 'files':files};
}

module.exports = initUIEventsFiles;